name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: zainalsalamun/binar-platinum-frontend
          path: frontend

      - name: Setup Node.js environment for frontend
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Deploy frontend to Vercel
        if: github.ref == 'refs/heads/main' # Deploy only on main branch
        run: |
          npm install -g vercel
          npm run build --prefix frontend
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
